[package]
name = "safecloset"
version = "0.1.0"
edition = "2018"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/safecloset"
description = "Secret Keeper"
keywords = ["secret", "tui", "cryptography", "password"]
license = "AGPL-3.0"
categories = ["command-line-interface", "cryptography"]
readme = "README.md"

[dependencies]
aes-gcm-siv = "0.10.2"
argh = "0.1.5"
cli-log = "2.0.0"
crossterm = "0.20.0"
minimad = "0.8.0"
log = "0.4.14"
rand = "0.8.4"
rust-argon2 = "0.8.3"
serde = { version = "1.0.128", features = ["derive"] }
serde_json = "1.0.66"
termimad = "0.14.2"
thiserror = "1.0.26"

[dev-dependencies]
tempfile = "3.2.0"

[profile.release]
lto = true

