[package]
name = "safecloset"
version = "0.2.1"
edition = "2018"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/safecloset"
description = "Secret Keeper"
keywords = ["secret", "tui", "cryptography", "password"]
license = "AGPL-3.0"
categories = ["command-line-interface", "cryptography"]
readme = "README.md"

[dependencies]
aes-gcm-siv = "0.10.2"
argh = "0.1.5"
cli-log = "2.0.0"
crossbeam = "0.8"
crossterm = "0.21.0"
minimad = "0.8.0"
log = "0.4.14"
rand = "0.8.4"
rmp-serde = "0.15.5"
rust-argon2 = "0.8.3"
secular = { version = "1.0", features = ["normalization"] }
serde = { version = "1.0.128", features = ["derive"] }
termimad = "0.16.1"
thiserror = "1.0.26"
unicode-width = "0.1.8"

[dev-dependencies]
tempfile = "3.2.0"

[profile.release]
lto = true

[patch.crates-io]
# termimad = { path = "../termimad" }
